name: frontend_flutter
description: A simplified Tashilat frontend using Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # === Ø§Ù„Ø¥Ø¶Ø§ÙØ© Ø§Ù„Ø¶Ø±ÙˆØ±ÙŠØ© Ù„Ø¯Ø¹Ù… Ø§Ù„Ù„ØºØ© Ø§Ù„Ø¹Ø±Ø¨ÙŠØ© ÙˆØ§Ù„Ù€ RTL ===
  flutter_localizations:
    sdk: flutter
  # ===================================================

  http: ^1.1.2
  image_picker: ^1.1.2
  
  # âœ… ØªÙ… ØªØµØ­ÙŠØ­ Ù‡Ø°Ø§ Ø§Ù„Ù‚ÙŠØ¯ Ù„ÙŠØªÙˆØ§ÙÙ‚ Ù…Ø¹ Ù…ØªØ·Ù„Ø¨Ø§Øª flutter_localizations
  intl: ^0.20.2 
  
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # âœ… ØªÙ…Øª Ø¥Ø¶Ø§ÙØ© Ø­Ø²Ù…Ø© flutter_svg Ø§Ù„Ù…Ø·Ù„ÙˆØ¨Ø© Ù„Ø¹Ø±Ø¶ Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø©
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  
  # ðŸ›‘ ØªØ£ÙƒØ¯ Ù…Ù† Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø¬Ù„Ø¯ "assets" ÙÙŠ Ø¬Ø°Ø± Ø§Ù„Ù…Ø´Ø±ÙˆØ¹ ÙˆÙˆØ¶Ø¹ Ø§Ù„Ù…Ù„ÙØ§Øª Ø§Ù„ØªØ§Ù„ÙŠØ© Ø¨Ø¯Ø§Ø®Ù„Ù‡.
  assets:
   - assets/images/
   - assets/seat_icon.svg # Ø§Ù„Ù…Ø³Ø§Ø± Ø§Ù„Ù…Ø·Ù„ÙˆØ¨ Ù„Ù…Ù„Ù Ø£ÙŠÙ‚ÙˆÙ†Ø© Ø§Ù„Ù…Ù‚Ø¹Ø¯

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21